### ISSUE TITLE
Support more planetary systems

### ISSUE THREAD

**Issue by alex-dev** [Gupyzer0/Spacelines-Progression#60]
How open would you be to supporting more planetary systems?
- Stock can be supported by reusing JNSQ pretty easily.
- OPM is likely to be as easy to support
- JNSQ with Principia will change the system quite a bit to keep everything stable
  - Minmus is moved inside Mun orbit: contracts should take it into consideration
  - Bop is retrograde: should not matter at all

**Comment by Gupyzer0** [comment]
Hi Alex, sorry for the late reply.

### About stock | OPM support
It's doable of course but for now I just wont,  I'll stay with JNSQ/ KSRSS and will consider other 2.5x / 2.7x scale solar systems once I consider this "first stage ready".

### About JNSQ + Principia
Yes! I'm aware of this change and Mun / Minmus contracts both appear at the same time (have the same requirements) so there's no problem with that. Even without Principia i'm aware of some people preffering to go for Minmus first for as Minmus offers an easier landing/ascent.
